# Generated by Django 3.2 on 2023-08-07 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1.'), django.core.validators.MaxValueValidator(100, message='Значение не может быть больше 1.')], verbose_name='Количество'),
        ),
    ]
